spring:
  datasource:
    url: @jdbc.url.dev@
    username: @jdbc.username.dev@
    password: @jdbc.password.dev@
  jpa:
    show-sql: true
  redis:
    host: @redis.url.dev@
  # rabbitmq test
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: @eureka.url.dev@

