spring:
  datasource:
    url: @jdbc.url.prod@
    username: @jdbc.username.prod@
    password: @jdbc.password.prod@
  jpa:
    show-sql: false
  redis:
    host: @redis.url.prod@
  # rabbitmq test
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: @eureka.url.prod@