spring:
  profiles:
    active: @devMode@
  application:
    name: api-gateway
  redis:
    database: 0
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000 # 连接超时时间（毫秒）, 2.x不能为0

server:
  port: 8008

#eureka:
#  client:
#    service-url:
#      # 本地配置
#      # defaultZone: http://localhost:8761/eureka/
#      # docker 配置
#      defaultZone: http://eureka-server:8761/eureka/

zuul:
  prefix: /api/v1
  #strip-prefix: false
  add-host-header: true #解决重定向问题, nginx
  sensitive-headers: #解决HTTP请求头信息中的Cookie和Authorization都没有被正确地传递给具体服务，所以最终导致会话状态没有得到保持的问题。
  routes:
    # yaml文件确保路由拦截顺序
    # 三种配置顺序
    shop-service:
      path: /shop-service/**
      serviceId: shop-service
    # 验证服务
    auth-service: /auth-service/**
    # 员工服务
    staff-service: /staff-service/**
    # 客户服务
    client-service: /client-service/**
    # common 服务
    common-service: /common-service/**
#    eureka-web: #单实例路由配置
#      path: /**
#      url: http://localhost:8008/eureka-web/

#Spring Security配置
#security:
#  user:
#    name: root
#    password: root

# 熔断器
hystrix:
  metrics:
    enabled: false